spring.application.name=SubscriptionbillingEngine

# ? PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://localhost:5433/subscription_db
spring.datasource.username=postgres
spring.datasource.password=Yash@#0005
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update